import os
import sys
import io
import argparse
from alembic.config import Config
from alembic import command
from alembic.script import ScriptDirectory
import contextlib

def main():
    parser = argparse.ArgumentParser(description="Generate Alembic migration and sync to Supabase SQL")
    parser.add_argument("--message", "-m", required=True, help="Migration message")
    args = parser.parse_args()
    
    backend_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    alembic_ini_path = os.path.join(backend_dir, "alembic.ini")
    supabase_migrations_dir = os.path.join(os.path.dirname(backend_dir), "infra", "supabase", "migrations")
    
    os.chdir(backend_dir)
    
    config = Config(alembic_ini_path)
    script = ScriptDirectory.from_config(config)
    
    head_before = script.get_current_head()
    
    # 1. Autogenerate python revision
    command.revision(config, autogenerate=True, message=args.message)
    
    # Reload script directory to get new head
    script = ScriptDirectory.from_config(config)
    head_after = script.get_current_head()
    
    if head_before == head_after:
        print("No schema changes detected.")
        sys.exit(0)
        
    print(f"Generated python migration: {head_after}")
    
    # 2. Capture SQL output for the new revision using PostgreSQL dialect
    # By forcing the sqlalchemy.url to postgresql, the SQL generated will be Postgres compatible
    config.set_main_option("sqlalchemy.url", "postgresql://user:pass@localhost/dummy")
    
    buf = io.StringIO()
    with contextlib.redirect_stdout(buf):
        rev_range = f"{head_before}:{head_after}" if head_before else head_after
        command.upgrade(config, rev_range, sql=True)
        
    sql_output = buf.getvalue()
    
    if not sql_output.strip():
        print("No SQL output generated.")
        sys.exit(0)
        
    # 3. Save to infra/supabase/migrations/
    existing_files = [f for f in os.listdir(supabase_migrations_dir) if f.endswith('.sql')]
    max_num = 0
    for f in existing_files:
        try:
            num = int(f.split('_')[0])
            max_num = max(max_num, num)
        except ValueError:
            pass
            
    next_num = max_num + 1
    safe_msg = args.message.replace(' ', '_').replace('-', '_').lower()
    filename = f"{next_num:05d}_{safe_msg}.sql"
    filepath = os.path.join(supabase_migrations_dir, filename)
    
    with open(filepath, "w") as f:
        f.write(f"-- Migration generated by Alembic Sync\n")
        f.write(f"-- Message: {args.message}\n")
        f.write(f"-- Revision: {head_after}\n\n")
        
        # Alembic generates transaction wrappers, we just write it all
        f.write(sql_output)
        
    print(f"Successfully generated Supabase migration: {filepath}")

if __name__ == "__main__":
    main()
