-- Migration generated by Alembic Sync
-- Message: test sync
-- Revision: 56e291fffba1

BEGIN;

-- Running upgrade 0001 -> 56e291fffba1

ALTER TABLE api_keys ALTER COLUMN id TYPE UUID;

ALTER TABLE api_keys ALTER COLUMN user_id TYPE UUID;

CREATE INDEX idx_api_keys_key_hash ON api_keys (key_hash) WHERE status = 'active';

ALTER TABLE api_keys ADD CONSTRAINT chk_api_keys_rate_limit CHECK (rate_limit_per_minute > 0);

ALTER TABLE audio_assets ALTER COLUMN id TYPE UUID;

ALTER TABLE audio_assets ALTER COLUMN user_id TYPE UUID;

ALTER TABLE audio_assets ALTER COLUMN channels TYPE INTEGER;

ALTER TABLE audio_assets ALTER COLUMN bit_depth TYPE INTEGER;

CREATE INDEX idx_audio_assets_content_hash ON audio_assets (content_hash);

ALTER TABLE audio_assets ADD CONSTRAINT chk_audio_bit_depth CHECK (bit_depth IN (8, 16, 24, 32));

ALTER TABLE audio_assets ADD CONSTRAINT chk_audio_channels CHECK (channels IN (1, 2));

ALTER TABLE audio_assets ADD CONSTRAINT chk_audio_duration CHECK (duration_seconds > 0);

ALTER TABLE audio_assets ADD CONSTRAINT chk_audio_file_size CHECK (file_size_bytes > 0);

ALTER TABLE audio_assets ADD CONSTRAINT chk_audio_sample_rate CHECK (sample_rate > 0);

ALTER TABLE speaker_profiles ALTER COLUMN id TYPE UUID;

ALTER TABLE speaker_profiles ALTER COLUMN user_id TYPE UUID;

ALTER TABLE speaker_profiles ALTER COLUMN reference_audio_id TYPE UUID;

CREATE INDEX idx_speaker_profiles_user_visibility ON speaker_profiles (user_id, visibility, is_active) WHERE deleted_at IS NULL;

ALTER TABLE synthesis_jobs ALTER COLUMN id TYPE UUID;

ALTER TABLE synthesis_jobs ALTER COLUMN user_id TYPE UUID;

ALTER TABLE synthesis_jobs ALTER COLUMN speaker_profile_id TYPE UUID;

ALTER TABLE synthesis_jobs ALTER COLUMN output_audio_id TYPE UUID;

CREATE INDEX idx_synthesis_jobs_task_id ON synthesis_jobs (task_id);

CREATE INDEX idx_synthesis_jobs_user_status_created ON synthesis_jobs (user_id, status, created_at);

ALTER TABLE synthesis_jobs ADD CONSTRAINT chk_synthesis_energy CHECK (energy_modifier BETWEEN 0.50 AND 2.00);

ALTER TABLE synthesis_jobs ADD CONSTRAINT chk_synthesis_pitch CHECK (pitch_modifier BETWEEN 0.50 AND 2.00);

ALTER TABLE synthesis_jobs ADD CONSTRAINT chk_synthesis_rtf CHECK (real_time_factor >= 0);

ALTER TABLE synthesis_jobs ADD CONSTRAINT chk_synthesis_speed CHECK (speed_modifier BETWEEN 0.50 AND 2.00);

ALTER TABLE synthesis_jobs ADD CONSTRAINT chk_synthesis_ttfb CHECK (ttfb_ms >= 0);

ALTER TABLE telemetry_metrics ALTER COLUMN id TYPE UUID;

ALTER TABLE telemetry_metrics ALTER COLUMN metric_value TYPE NUMERIC;

ALTER TABLE usage_logs ALTER COLUMN id TYPE UUID;

ALTER TABLE usage_logs ALTER COLUMN user_id TYPE UUID;

ALTER TABLE usage_logs ALTER COLUMN api_key_id TYPE UUID;

ALTER TABLE usage_logs ALTER COLUMN synthesis_job_id TYPE UUID;

ALTER TABLE usage_logs ADD CONSTRAINT chk_usage_characters CHECK (characters_count >= 0);

ALTER TABLE usage_logs ADD CONSTRAINT chk_usage_compute CHECK (compute_ms >= 0);

ALTER TABLE usage_logs ADD CONSTRAINT chk_usage_duration CHECK (audio_duration_seconds >= 0);

ALTER TABLE users ALTER COLUMN id TYPE UUID;

ALTER TABLE users ADD CONSTRAINT chk_users_api_quota CHECK (api_quota_monthly >= 0);

UPDATE alembic_version SET version_num='56e291fffba1' WHERE alembic_version.version_num = '0001';

COMMIT;

