"""test sync

Revision ID: 56e291fffba1
Revises: 0001
Create Date: 2026-08-14 22:18:00.146325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56e291fffba1'
down_revision: Union[str, Sequence[str], None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('api_keys', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('(lower(hex(randomblob(16))))'))
    op.alter_column('api_keys', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.create_index('idx_api_keys_key_hash', 'api_keys', ['key_hash'], unique=False, postgresql_where="status = 'active'")
    op.create_check_constraint('chk_api_keys_rate_limit', 'api_keys', 'rate_limit_per_minute > 0')
    op.alter_column('audio_assets', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('(lower(hex(randomblob(16))))'))
    op.alter_column('audio_assets', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('audio_assets', 'channels',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('audio_assets', 'bit_depth',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text("'16'"))
    op.create_index('idx_audio_assets_content_hash', 'audio_assets', ['content_hash'], unique=False)
    op.create_check_constraint('chk_audio_bit_depth', 'audio_assets', 'bit_depth IN (8, 16, 24, 32)')
    op.create_check_constraint('chk_audio_channels', 'audio_assets', 'channels IN (1, 2)')
    op.create_check_constraint('chk_audio_duration', 'audio_assets', 'duration_seconds > 0')
    op.create_check_constraint('chk_audio_file_size', 'audio_assets', 'file_size_bytes > 0')
    op.create_check_constraint('chk_audio_sample_rate', 'audio_assets', 'sample_rate > 0')
    op.alter_column('speaker_profiles', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('(lower(hex(randomblob(16))))'))
    op.alter_column('speaker_profiles', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('speaker_profiles', 'reference_audio_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.create_index('idx_speaker_profiles_user_visibility', 'speaker_profiles', ['user_id', 'visibility', 'is_active'], unique=False, postgresql_where='deleted_at IS NULL')
    op.alter_column('synthesis_jobs', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('(lower(hex(randomblob(16))))'))
    op.alter_column('synthesis_jobs', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('synthesis_jobs', 'speaker_profile_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('synthesis_jobs', 'output_audio_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.create_index('idx_synthesis_jobs_task_id', 'synthesis_jobs', ['task_id'], unique=False)
    op.create_index('idx_synthesis_jobs_user_status_created', 'synthesis_jobs', ['user_id', 'status', 'created_at'], unique=False)
    op.create_check_constraint('chk_synthesis_energy', 'synthesis_jobs', 'energy_modifier BETWEEN 0.50 AND 2.00')
    op.create_check_constraint('chk_synthesis_pitch', 'synthesis_jobs', 'pitch_modifier BETWEEN 0.50 AND 2.00')
    op.create_check_constraint('chk_synthesis_rtf', 'synthesis_jobs', 'real_time_factor >= 0')
    op.create_check_constraint('chk_synthesis_speed', 'synthesis_jobs', 'speed_modifier BETWEEN 0.50 AND 2.00')
    op.create_check_constraint('chk_synthesis_ttfb', 'synthesis_jobs', 'ttfb_ms >= 0')
    op.alter_column('telemetry_metrics', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('(lower(hex(randomblob(16))))'))
    op.alter_column('telemetry_metrics', 'metric_value',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(),
               existing_nullable=False)
    op.alter_column('usage_logs', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('(lower(hex(randomblob(16))))'))
    op.alter_column('usage_logs', 'user_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('usage_logs', 'api_key_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.alter_column('usage_logs', 'synthesis_job_id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.create_check_constraint('chk_usage_characters', 'usage_logs', 'characters_count >= 0')
    op.create_check_constraint('chk_usage_compute', 'usage_logs', 'compute_ms >= 0')
    op.create_check_constraint('chk_usage_duration', 'usage_logs', 'audio_duration_seconds >= 0')
    op.alter_column('users', 'id',
               existing_type=sa.NUMERIC(),
               type_=sa.UUID(),
               existing_nullable=False,
               existing_server_default=sa.text('(lower(hex(randomblob(16))))'))
    op.create_check_constraint('chk_users_api_quota', 'users', 'api_quota_monthly >= 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chk_users_api_quota', 'users', type_='check')
    op.alter_column('users', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False,
               existing_server_default=sa.text('(lower(hex(randomblob(16))))'))
    op.drop_constraint('chk_usage_duration', 'usage_logs', type_='check')
    op.drop_constraint('chk_usage_compute', 'usage_logs', type_='check')
    op.drop_constraint('chk_usage_characters', 'usage_logs', type_='check')
    op.alter_column('usage_logs', 'synthesis_job_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('usage_logs', 'api_key_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('usage_logs', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('usage_logs', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False,
               existing_server_default=sa.text('(lower(hex(randomblob(16))))'))
    op.alter_column('telemetry_metrics', 'metric_value',
               existing_type=sa.Numeric(),
               type_=sa.FLOAT(),
               existing_nullable=False)
    op.alter_column('telemetry_metrics', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False,
               existing_server_default=sa.text('(lower(hex(randomblob(16))))'))
    op.drop_constraint('chk_synthesis_ttfb', 'synthesis_jobs', type_='check')
    op.drop_constraint('chk_synthesis_speed', 'synthesis_jobs', type_='check')
    op.drop_constraint('chk_synthesis_rtf', 'synthesis_jobs', type_='check')
    op.drop_constraint('chk_synthesis_pitch', 'synthesis_jobs', type_='check')
    op.drop_constraint('chk_synthesis_energy', 'synthesis_jobs', type_='check')
    op.drop_index('idx_synthesis_jobs_user_status_created', table_name='synthesis_jobs')
    op.drop_index('idx_synthesis_jobs_task_id', table_name='synthesis_jobs')
    op.alter_column('synthesis_jobs', 'output_audio_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('synthesis_jobs', 'speaker_profile_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('synthesis_jobs', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('synthesis_jobs', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False,
               existing_server_default=sa.text('(lower(hex(randomblob(16))))'))
    op.drop_index('idx_speaker_profiles_user_visibility', table_name='speaker_profiles', postgresql_where='deleted_at IS NULL')
    op.alter_column('speaker_profiles', 'reference_audio_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('speaker_profiles', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('speaker_profiles', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False,
               existing_server_default=sa.text('(lower(hex(randomblob(16))))'))
    op.drop_constraint('chk_audio_sample_rate', 'audio_assets', type_='check')
    op.drop_constraint('chk_audio_file_size', 'audio_assets', type_='check')
    op.drop_constraint('chk_audio_duration', 'audio_assets', type_='check')
    op.drop_constraint('chk_audio_channels', 'audio_assets', type_='check')
    op.drop_constraint('chk_audio_bit_depth', 'audio_assets', type_='check')
    op.drop_index('idx_audio_assets_content_hash', table_name='audio_assets')
    op.alter_column('audio_assets', 'bit_depth',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=False,
               existing_server_default=sa.text("'16'"))
    op.alter_column('audio_assets', 'channels',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('audio_assets', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=True)
    op.alter_column('audio_assets', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False,
               existing_server_default=sa.text('(lower(hex(randomblob(16))))'))
    op.drop_constraint('chk_api_keys_rate_limit', 'api_keys', type_='check')
    op.drop_index('idx_api_keys_key_hash', table_name='api_keys', postgresql_where="status = 'active'")
    op.alter_column('api_keys', 'user_id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.alter_column('api_keys', 'id',
               existing_type=sa.UUID(),
               type_=sa.NUMERIC(),
               existing_nullable=False,
               existing_server_default=sa.text('(lower(hex(randomblob(16))))'))
    # ### end Alembic commands ###
